language: java

cache:
  directories:
    - $HOME/.gradle/caches/

install:
  - git clone git://github.com/JetBrains/Arend && cd Arend
  - ./gradlew
  - ./gradlew jarDep
  - cd ..

script:
  - java -jar ./Arend/build/libs/arend.jar -s src
