\import Connection
\import Path
\import Equiv
\import S1
\import Iso
\import Univ

\func neg-neg (x : I) : neg (neg x) = x
   => inv (connAnd (inv seg) (neg x)) # I-contr-right x

\func twist : I = I => Iso=>Path
   \new Iso I I neg neg neg-neg neg-neg

\func M : \Pi (x : S1) -> \Type => \lam x => \case x \with {
   | base => I
   | loop i => twist @ i
}

\record Moebius (p1 : S1) {
   \field f1 : M(p1)
}