\import Connection
\import Path
\import Equiv
\import S1
\import Iso
\import Univ

\func negate-negate (x : I) : negate (negate x) = x
   => inv (connAnd (inv seg) (negate x)) # I-contr-right x

\func twist : I = I => Iso=>Path
   \new Iso I I negate negate negate-negate negate-negate

\func M : \Pi (x : S1) -> \Type => \lam x => \case x \with {
   | base => I
   | loop i => twist @ i
}

\record Moebius (p1 : S1) {
   \field f1 : M(p1)
}