name: arend

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Arend
        run: wget https://github.com/JetBrains/Arend/releases/latest/download/Arend.jar

      - name: Check library
        run: java -jar Arend.jar -s src

